source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CLBanner_Example', :exclusive => true do
  pod "CLBanner", :path => "../"
end

target 'CLBanner_Tests', :exclusive => true do
  pod "CLBanner", :path => "../"

  
end
